version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=openfabric
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
